title = "wiki"
baseURL = 'https://example.org'
languageCode = 'en-us'

[params]
  # "relatedtext" is the text that appears above the tag list at the bottom of pages.
  #relatedtext = "Related:"
  favicon = "/favicon.ico"

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false
